import type { ActionCard } from '$lib/types/tile';

// ─── CHANCE (KESEMPATAN) DECK ───────────────────────────────────────────
// Classic Monopoly: 16 Chance cards
export const chanceCards: ActionCard[] = [
    {
        id: 0,
        deck: 'CHANCE',
        title: 'Maju ke Mulai',
        description: 'Majulah ke petak MULAI. Terima 200M.',
        action: 'move_to',
        value: 0,
    },
    {
        id: 1,
        deck: 'CHANCE',
        title: 'Pergi ke Jakarta',
        description: 'Majulah ke Jakarta (DKI). Jika melewati Mulai, terima 200M.',
        action: 'move_to',
        value: 39,
    },
    {
        id: 2,
        deck: 'CHANCE',
        title: 'Pergi ke Palembang',
        description: 'Majulah ke Palembang. Jika melewati Mulai, terima 200M.',
        action: 'move_to',
        value: 21,
    },
    {
        id: 3,
        deck: 'CHANCE',
        title: 'Pergi ke Stasiun Gambir',
        description: 'Majulah ke Stasiun Gambir. Jika melewati Mulai, terima 200M.',
        action: 'move_to',
        value: 5,
    },
    {
        id: 4,
        deck: 'CHANCE',
        title: 'Pergi ke Solo',
        description: 'Majulah ke Solo. Jika melewati Mulai, terima 200M.',
        action: 'move_to',
        value: 11,
    },
    {
        id: 5,
        deck: 'CHANCE',
        title: 'Stasiun Terdekat',
        description: 'Majulah ke stasiun kereta api terdekat. Jika dimiliki pemain lain, bayar 2x sewa normal.',
        action: 'advance_to_nearest_railroad',
    },
    {
        id: 6,
        deck: 'CHANCE',
        title: 'Stasiun Terdekat',
        description: 'Majulah ke stasiun kereta api terdekat. Jika dimiliki pemain lain, bayar 2x sewa normal.',
        action: 'advance_to_nearest_railroad',
    },
    {
        id: 7,
        deck: 'CHANCE',
        title: 'Utilitas Terdekat',
        description: 'Majulah ke utilitas terdekat. Jika dimiliki pemain lain, lempar dadu dan bayar 10x hasilnya.',
        action: 'advance_to_nearest_utility',
    },
    {
        id: 8,
        deck: 'CHANCE',
        title: 'Dividen Bank',
        description: 'Bank membayar dividen sebesar 50M kepadamu.',
        action: 'collect',
        value: 50,
    },
    {
        id: 9,
        deck: 'CHANCE',
        title: 'Mundur 3 Langkah',
        description: 'Mundur 3 langkah ke belakang.',
        action: 'move_back',
        value: 3,
    },
    {
        id: 10,
        deck: 'CHANCE',
        title: 'Masuk Penjara!',
        description: 'Pergi langsung ke Penjara. Jangan lewat Mulai, jangan terima 200M.',
        action: 'go_to_jail',
    },
    {
        id: 11,
        deck: 'CHANCE',
        title: 'Perbaikan Umum',
        description: 'Lakukan perbaikan pada semua propertimu. Bayar 100M ke Bank.',
        action: 'repairs',
        value: 100,
        perHouse: 25,
        perHotel: 100,
    },
    {
        id: 12,
        deck: 'CHANCE',
        title: 'Denda Kecepatan',
        description: 'Kamu melanggar batas kecepatan. Bayar denda 15M.',
        action: 'pay',
        value: 15,
    },
    {
        id: 13,
        deck: 'CHANCE',
        title: 'Perjalanan ke Bandung',
        description: 'Kamu pergi wisata ke Stasiun Bandung. Jika melewati Mulai, terima 200M.',
        action: 'move_to',
        value: 15,
    },
    {
        id: 14,
        deck: 'CHANCE',
        title: 'Terpilih Jadi Ketua',
        description: 'Kamu terpilih jadi ketua RT. Bayar 50M ke setiap pemain.',
        action: 'pay_each_player',
        value: 50,
    },
    {
        id: 15,
        deck: 'CHANCE',
        title: 'Pinjaman Jatuh Tempo',
        description: 'Pinjaman investasimu jatuh tempo. Terima 150M.',
        action: 'collect',
        value: 150,
    },
];

// ─── COMMUNITY CHEST (DANA UMUM) DECK ──────────────────────────────────
// Classic Monopoly: 16 Community Chest cards
export const communityChestCards: ActionCard[] = [
    {
        id: 0,
        deck: 'COMMUNITY_CHEST',
        title: 'Maju ke Mulai',
        description: 'Majulah ke petak MULAI. Terima 200M.',
        action: 'move_to',
        value: 0,
    },
    {
        id: 1,
        deck: 'COMMUNITY_CHEST',
        title: 'Kekeliruan Bank',
        description: 'Kekeliruan bank menguntungkanmu. Terima 200M.',
        action: 'collect',
        value: 200,
    },
    {
        id: 2,
        deck: 'COMMUNITY_CHEST',
        title: 'Biaya Dokter',
        description: 'Bayar biaya dokter sebesar 50M.',
        action: 'pay',
        value: 50,
    },
    {
        id: 3,
        deck: 'COMMUNITY_CHEST',
        title: 'Penjualan Saham',
        description: 'Kamu menjual sahammu dan mendapat keuntungan 50M.',
        action: 'collect',
        value: 50,
    },
    {
        id: 4,
        deck: 'COMMUNITY_CHEST',
        title: 'Masuk Penjara!',
        description: 'Pergi langsung ke Penjara. Jangan lewat Mulai, jangan terima 200M.',
        action: 'go_to_jail',
    },
    {
        id: 5,
        deck: 'COMMUNITY_CHEST',
        title: 'Hari Ulang Tahun',
        description: 'Selamat ulang tahun! Terima 10M dari setiap pemain.',
        action: 'collect_each_player',
        value: 10,
    },
    {
        id: 6,
        deck: 'COMMUNITY_CHEST',
        title: 'Pengembalian Pajak',
        description: 'Kamu mendapat pengembalian pajak penghasilan sebesar 20M.',
        action: 'collect',
        value: 20,
    },
    {
        id: 7,
        deck: 'COMMUNITY_CHEST',
        title: 'Asuransi Jiwa',
        description: 'Asuransi jiwa jatuh tempo. Terima 100M.',
        action: 'collect',
        value: 100,
    },
    {
        id: 8,
        deck: 'COMMUNITY_CHEST',
        title: 'Biaya Rumah Sakit',
        description: 'Bayar biaya rumah sakit sebesar 100M.',
        action: 'pay',
        value: 100,
    },
    {
        id: 9,
        deck: 'COMMUNITY_CHEST',
        title: 'Biaya Sekolah',
        description: 'Bayar biaya pendidikan sebesar 50M.',
        action: 'pay',
        value: 50,
    },
    {
        id: 10,
        deck: 'COMMUNITY_CHEST',
        title: 'Jasa Konsultan',
        description: 'Kamu mendapat bayaran jasa konsultan sebesar 25M.',
        action: 'collect',
        value: 25,
    },
    {
        id: 11,
        deck: 'COMMUNITY_CHEST',
        title: 'Perbaikan Jalan',
        description: 'Bayar perbaikan jalan sebesar 115M.',
        action: 'repairs',
        value: 115,
        perHouse: 40,
        perHotel: 115,
    },
    {
        id: 12,
        deck: 'COMMUNITY_CHEST',
        title: 'Juara Kedua Kontes',
        description: 'Kamu memenangkan juara kedua kontes kecantikan. Terima 10M.',
        action: 'collect',
        value: 10,
    },
    {
        id: 13,
        deck: 'COMMUNITY_CHEST',
        title: 'Warisan',
        description: 'Kamu menerima warisan sebesar 100M.',
        action: 'collect',
        value: 100,
    },
    {
        id: 14,
        deck: 'COMMUNITY_CHEST',
        title: 'Bunga Tabungan',
        description: 'Tabunganmu menghasilkan bunga. Terima 25M.',
        action: 'collect',
        value: 25,
    },
    {
        id: 15,
        deck: 'COMMUNITY_CHEST',
        title: 'Bonus Liburan',
        description: 'Kamu mendapatkan bonus liburan dari kantor. Terima 50M.',
        action: 'collect',
        value: 50,
    },
];
