import { ColorGroup, type BoardTile, TileType } from "$lib/types/tile";

export const tiles: BoardTile[] = [
    {
        id: 0,
        name: "Mulai",
        displayName: "Mulai",
        type: TileType.Action,
        actionType: "GO",
    },
    {
        id: 1,
        name: "Depok",
        displayName: "Depok",
        type: TileType.Street,
        color: ColorGroup.Brown,
        price: { base: 60, house: 50, mortgage: 30 },
        rent: { base: 2, monopoly: 4, 1: 10, 2: 30, 3: 90, 4: 160, hotel: 250 },
    },
    {
        id: 2,
        name: "Dana Umum",
        displayName: "Dana Umum",
        type: TileType.Action,
        actionType: "COMMUNITY_CHEST",
    },
    {
        id: 3,
        name: "Bekasi",
        displayName: "Bekasi",
        type: TileType.Street,
        color: ColorGroup.Brown,
        price: { base: 60, house: 50, mortgage: 30 },
        rent: { base: 4, monopoly: 8, 1: 20, 2: 60, 3: 180, 4: 320, hotel: 450 },
    },
    {
        id: 4,
        name: "Pajak",
        displayName: "Pajak",
        type: TileType.Tax,
        cost: 200,
    },
    {
        id: 5,
        name: "Stasiun Gambir",
        displayName: "Stasiun Gambir",
        type: TileType.Railroad,
        price: { base: 200, mortgage: 100 },
        rent: [25, 50, 100, 200],
    },
    {
        id: 6,
        name: "Bogor",
        displayName: "Bogor",
        type: TileType.Street,
        color: ColorGroup.LightBlue,
        price: { base: 100, house: 50, mortgage: 50 },
        rent: { base: 6, monopoly: 12, 1: 30, 2: 90, 3: 270, 4: 400, hotel: 550 },
    },
    {
        id: 7,
        name: "Kesempatan",
        displayName: "?",
        type: TileType.Action,
        actionType: "CHANCE",
    },
    {
        id: 8,
        name: "Lampung",
        displayName: "LA",
        type: TileType.Street,
        color: ColorGroup.LightBlue,
        price: { base: 100, house: 50, mortgage: 50 },
        rent: { base: 6, monopoly: 12, 1: 30, 2: 90, 3: 270, 4: 400, hotel: 550 },
    },
    {
        id: 9,
        name: "Bandung",
        displayName: "BDG",
        type: TileType.Street,
        color: ColorGroup.LightBlue,
        price: { base: 120, house: 50, mortgage: 60 },
        rent: { base: 8, monopoly: 16, 1: 40, 2: 100, 3: 300, 4: 450, hotel: 600 },
    },
    {
        id: 10,
        name: "Penjara",
        displayName: "Penjara",
        type: TileType.Action,
        actionType: "JAIL",
    },
    {
        id: 11,
        name: "Solo",
        displayName: "SOLO",
        type: TileType.Street,
        color: ColorGroup.Pink,
        price: { base: 140, house: 100, mortgage: 70 },
        rent: { base: 10, monopoly: 20, 1: 50, 2: 150, 3: 450, 4: 625, hotel: 750 },
    },
    {
        id: 12,
        name: "PLN",
        displayName: "PLN",
        type: TileType.Utility,
        price: { base: 150, mortgage: 75 },
        multipliers: [4, 10],
    },
    {
        id: 13,
        name: "Semarang",
        displayName: "SMG",
        type: TileType.Street,
        color: ColorGroup.Pink,
        price: { base: 140, house: 100, mortgage: 70 },
        rent: { base: 10, monopoly: 20, 1: 50, 2: 150, 3: 450, 4: 625, hotel: 750 },
    },
    {
        id: 14,
        name: "Yogyakarta",
        displayName: "JOGJA",
        type: TileType.Street,
        color: ColorGroup.Pink,
        price: { base: 160, house: 100, mortgage: 80 },
        rent: { base: 12, monopoly: 24, 1: 60, 2: 180, 3: 500, 4: 700, hotel: 900 },
    },
    {
        id: 15,
        name: "Stasiun Bandung",
        displayName: "Stasiun Hall",
        type: TileType.Railroad,
        price: { base: 200, mortgage: 100 },
        rent: [25, 50, 100, 200],
    },
    {
        id: 16,
        name: "Malang",
        displayName: "MLG",
        type: TileType.Street,
        color: ColorGroup.Orange,
        price: { base: 180, house: 100, mortgage: 90 },
        rent: { base: 14, monopoly: 28, 1: 70, 2: 200, 3: 550, 4: 750, hotel: 950 },
    },
    {
        id: 17,
        name: "Dana Umum",
        displayName: "Dana Umum",
        type: TileType.Action,
        actionType: "COMMUNITY_CHEST",
    },
    {
        id: 18,
        name: "Batu",
        displayName: "Batu",
        type: TileType.Street,
        color: ColorGroup.Orange,
        price: { base: 180, house: 100, mortgage: 90 },
        rent: { base: 14, monopoly: 28, 1: 70, 2: 200, 3: 550, 4: 750, hotel: 950 },
    },
    {
        id: 19,
        name: "Surabaya",
        displayName: "SBY",
        type: TileType.Street,
        color: ColorGroup.Orange,
        price: { base: 200, house: 100, mortgage: 100 },
        rent: { base: 16, monopoly: 32, 1: 80, 2: 220, 3: 600, 4: 800, hotel: 1000 },
    },
    {
        id: 20,
        name: "Parkir Gratis",
        displayName: "Parkir Gratis",
        type: TileType.Action,
        actionType: "FREE_PARKING",
    },
    {
        id: 21,
        name: "Palembang",
        displayName: "PLG",
        type: TileType.Street,
        color: ColorGroup.Red,
        price: { base: 220, house: 150, mortgage: 110 },
        rent: { base: 18, monopoly: 36, 1: 90, 2: 250, 3: 700, 4: 875, hotel: 1050 },
    },
    {
        id: 22,
        name: "Kesempatan",
        displayName: "?",
        type: TileType.Action,
        actionType: "CHANCE",
    },
    {
        id: 23,
        name: "Batam",
        displayName: "Batam",
        type: TileType.Street,
        color: ColorGroup.Red,
        price: { base: 220, house: 150, mortgage: 110 },
        rent: { base: 18, monopoly: 36, 1: 90, 2: 250, 3: 700, 4: 875, hotel: 1050 },
    },
    {
        id: 24,
        name: "Medan",
        displayName: "Medan",
        type: TileType.Street,
        color: ColorGroup.Red,
        price: { base: 240, house: 150, mortgage: 120 },
        rent: { base: 20, monopoly: 40, 1: 100, 2: 300, 3: 750, 4: 925, hotel: 1100 },
    },
    {
        id: 25,
        name: "Stasiun Tugu",
        displayName: "Stasiun Tugu",
        type: TileType.Railroad,
        price: { base: 200, mortgage: 100 },
        rent: [25, 50, 100, 200],
    },
    {
        id: 26,
        name: "Balikpapan",
        displayName: "Balik Papan",
        type: TileType.Street,
        color: ColorGroup.Yellow,
        price: { base: 260, house: 150, mortgage: 130 },
        rent: { base: 22, monopoly: 44, 1: 110, 2: 330, 3: 800, 4: 975, hotel: 1150 },
    },
    {
        id: 27,
        name: "Samarinda",
        displayName: "SMR",
        type: TileType.Street,
        color: ColorGroup.Yellow,
        price: { base: 260, house: 150, mortgage: 130 },
        rent: { base: 22, monopoly: 44, 1: 110, 2: 330, 3: 800, 4: 975, hotel: 1150 },
    },
    {
        id: 28,
        name: "PDAM",
        displayName: "PDAM",
        type: TileType.Utility,
        price: { base: 150, mortgage: 75 },
        multipliers: [4, 10],
    },
    {
        id: 29,
        name: "Makassar",
        displayName: "MKS",
        type: TileType.Street,
        color: ColorGroup.Yellow,
        price: { base: 280, house: 150, mortgage: 140 },
        rent: { base: 24, monopoly: 48, 1: 120, 2: 360, 3: 850, 4: 1025, hotel: 1200 },
    },
    {
        id: 30,
        name: "Masuk Penjara",
        displayName: "Masuk Penjara",
        type: TileType.Action,
        actionType: "GO_TO_JAIL",
    },
    {
        id: 31,
        name: "Lombok",
        displayName: "LBK",
        type: TileType.Street,
        color: ColorGroup.Green,
        price: { base: 300, house: 200, mortgage: 150 },
        rent: { base: 26, monopoly: 52, 1: 130, 2: 390, 3: 900, 4: 1100, hotel: 1275 },
    },
    {
        id: 32,
        name: "Bali",
        displayName: "Bali",
        type: TileType.Street,
        color: ColorGroup.Green,
        price: { base: 300, house: 200, mortgage: 150 },
        rent: { base: 26, monopoly: 52, 1: 130, 2: 390, 3: 900, 4: 1100, hotel: 1275 },
    },
    {
        id: 33,
        name: "Dana Umum",
        displayName: "Dana Umum",
        type: TileType.Action,
        actionType: "COMMUNITY_CHEST",
    },
    {
        id: 34,
        name: "Raja Ampat",
        displayName: "Raja Ampat",
        type: TileType.Street,
        color: ColorGroup.Green,
        price: { base: 320, house: 200, mortgage: 160 },
        rent: { base: 28, monopoly: 56, 1: 150, 2: 450, 3: 1000, 4: 1200, hotel: 1400 },
    },
    {
        id: 35,
        name: "Stasiun Solo Balapan",
        displayName: "Stasiun Solo",
        type: TileType.Railroad,
        price: { base: 200, mortgage: 100 },
        rent: [25, 50, 100, 200],
    },
    {
        id: 36,
        name: "Kesempatan",
        displayName: "?",
        type: TileType.Action,
        actionType: "CHANCE",
    },
    {
        id: 37,
        name: "Ibukota Nusantara",
        displayName: "IKN",
        type: TileType.Street,
        color: ColorGroup.DarkBlue,
        price: { base: 350, house: 200, mortgage: 175 },
        rent: { base: 35, monopoly: 70, 1: 175, 2: 500, 3: 1100, 4: 1300, hotel: 1500 },
    },
    {
        id: 38,
        name: "Pajak",
        displayName: "Pajak",
        type: TileType.Tax,
        cost: 100,
    },
    {
        id: 39,
        name: "Jakarta",
        displayName: "DKI",
        type: TileType.Street,
        color: ColorGroup.DarkBlue,
        price: { base: 400, house: 200, mortgage: 200 },
        rent: { base: 50, monopoly: 100, 1: 200, 2: 600, 3: 1400, 4: 1700, hotel: 2000 },
    },
];